logging:
  config: classpath:logback-${spring.profiles.active}.xml

spring:
  profiles:
    active: pro

  # mysql 配置
  datasource:
    # 数据源/连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
    sql-script-encoding: utf-8
    # 数据库驱动名称
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    druid:
      # 定义初始连接数
      initialSize: 1
      # 定义最小空闲 minIdle=1
      minIdle: 3
      # 定义最大连接数
      maxActive: 50
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      # 验证使用的SQL语句
      validationQuery: select 'x'
      # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
      testWhileIdle: true
      # 借出连接时不要测试，否则很影响性能
      testOnBorrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      # 指定每个连接上PSCache的大小
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    schema:
      - classpath:streammedia.sql

http-client:
  #连接池的最大连接数，0代表不限；如果取0，需要考虑连接泄露导致系统崩溃的后果
  maxTotalConnect: 1000
  #每个路由的最大连接数,如果只调用一个地址,可以将其设置为最大连接数
  maxConnectPerRoute: 200
  # 指客户端和服务器建立连接的超时时间,ms , 最大约21秒,因为内部tcp在进行三次握手建立连接时,默认tcp超时时间是20秒
  connectTimeout: 30000
  # 指客户端从服务器读取数据包的间隔超时时间,不是总读取时间,也就是socket timeout,ms
  readTimeout: 50000
  # 从连接池获取连接的timeout,不宜过大,ms
  connectionRequestTimout: 2000
  # 重试次数
  retryTimes: 1
  charset: UTF-8
  # 长连接保持时间 单位s,不宜过长
  keepAliveTime: 10
  # 针对不同的网址,长连接保持的存活时间,单位s,如果是频繁而持续的请求,可以设置小一点,不建议设置过大,避免大量无用连接占用内存资源
#  keepAliveTargetHost:
#    www.baidu.com: 5

swagger:
  enabled: true
  title:  推流器
  description: 推流器接口文档
  version: 1.0
  license: Apache License, Version 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: 贾荣
    email: rong.jia@unionman.com.cn
  base-package: cn.darkjrong.streamingmedia.controller
  base-path: /**

mybatis:
  # 映射文件所在路径
  mapper-locations: classpath:mappers/*.xml
  # pojo类所在包路径
  type-aliases-package: cn.darkjrong.streamingmedia.common.pojo.entity
  configuration:
    use-generated-keys: false
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

#  Mybatis 主键策略
key-plugin:
  enabled: true
  key-type: 2
